resolver: clash-HEAD.yaml

extra-deps:
  - barbies-2.0.1.0
  - barbies-th-0.1.2

  - terminal-0.2.0.0

  - github: emilypi/smash
    commit: bd3ae30bdfef3f92ce5575a1ee10228830afa11b
    subdirs:
      - smash-core

  - github: gergoerdi/clashilator
    commit: 564f21dd972dc12f11aa97e08d01ede8ebfbd5b5

packages:
  - retroclash-lib
  - retroclash-sim
  - clash-shake
  - clash-intel8080
  - .
